[GWS-97] added title bar component
edekadigital/backoffice-ui pull request #38
Opened 2020-09-29 12:32 UTC by freddakine

2020-10-06 14:28 UTC, antokro requested changes

2020-10-06 14:28 UTC, antokro commented on src/components/TitleBar.tsx
> +    minHeight: theme.spacing(7.25),
Prüfen ob 0.5 Schritte auch ok sind und gut aussehen

2020-10-07 07:49 UTC, freddakine commented on src/components/TitleBar.tsx
> +    minHeight: theme.spacing(7.25),
habe es jetzt fix auf 60px gesetzt.

2020-10-07 12:33 UTC, antokro approved these changes

2020-10-07 12:34 UTC, merged