Feature/gws 95 expandable list
edekadigital/backoffice-ui pull request #41
Opened 2020-10-08 17:08 UTC by antokro

2020-10-08 17:12 UTC, antokro commented on src/components/ExpandableList.tsx
> +    initialItems = [{ value: '' }, { value: '' }, { value: '' }],
Wenn ich statt undefined, einen leeren string nehme, dann kommt die Fehlermeldung mit controlled und uncontrolled component nicht. Anscheinend macht react da einen Unterschied, ich habe es jetzt so gelassen.

2020-10-09 11:11 UTC, freddakine requested changes

2020-10-09 11:11 UTC, freddakine commented on src/components/ExpandableList.tsx
> +      newItems[index].checked = !newItems[index].checked;
Default auf Multiple ändern (bei `true`)

2020-10-09 11:11 UTC, freddakine commented on src/components/ExpandableList.tsx
> +  const iconColor = checked ? '#4caf50' : undefined;
`const theme = useTheme<Theme>();
  theme.palette.success.main`

2020-10-09 11:11 UTC, freddakine commented on src/components/ExpandableList.tsx
> +  const iconColor = checked ? '#4caf50' : undefined;
oder alternativ über css klasse in Verbindung mit clsx

2020-10-09 11:11 UTC, freddakine commented on src/components/ExpandableList.spec.tsx
> +    expect(
zusätzlich in onChange prüfen, ob das richtige Item auf checked gesetzt wurde

2020-10-12 09:43 UTC, freddakine approved these changes

2020-10-12 09:44 UTC, merged