Add background color to body component
edekadigital/backoffice-ui pull request #65
Opened 2021-01-21 15:48 UTC by antokro

2021-01-21 16:06 UTC, schapka requested changes

2021-01-21 16:06 UTC, schapka commented on src/typography/Body.tsx
> +    const backgroundColorMap: { [k: string]: string } = {
Hier könnte man als Type `Record< BodyBackgroundColor, string>` verwenden und entsprechend noch `initial: theme.palette.background.default` ergänzen.

Dann würde die Zuweisung im nächsten Schritt so aussehen:
`backgroundColor: backgroundColorMap[sanitizedBackgroundColorName],`

2021-01-21 16:06 UTC, schapka commented on src/typography/Body.tsx
> +      padding: backgroundColor ? '20px' : '0px',
Ich fände es besser, wenn wir den Padding unabhängig der Hintergrundfarbe definieren würden. Also über eine Prop.

Beispielsweise ein Boolean "dense" (default = true, um abwärts kompatibel zu bleiben).
`padding: dense ? 0 : theme.spacing(2.5)`

Gerne auch über eine Prop, jedoch lieber nicht implizit abhängig zur Hintergrundfarbe.

2021-01-21 17:00 UTC, schapka requested changes

2021-01-21 17:00 UTC, schapka commented on src/typography/Body.tsx
> +   * @default false
In der Dokumentation muss der default value noch angepasst werden (=> true)

2021-01-21 17:04 UTC, schapka approved these changes

2021-01-22 12:05 UTC, freddakine approved these changes

2021-01-22 15:06 UTC, merged