Feature/loader
edekadigital/backoffice-ui pull request #74
Opened 2021-02-24 17:05 UTC by antokro

2021-02-24 17:06 UTC, antokro commented on src/forms/FormRow.tsx
> +    alignItems: 'center',
Habe ich hinzugefügt um Icon und Text auf eine Linie zu bekommen, ich bin durch das Story book gegangen, und habe keine Auswirkungen auf die Layouts gefunden.

2021-02-24 17:09 UTC, antokro commented on src/layouts/GridRow.tsx
> +    gutterBottom: gutterBottom === true ? 1.5 : +gutterBottom,
Die GridRow hat bereits `alignItems: 'center'`, daher habe ich hier noch ein freisetzbares `gutterBottom` und `gutterTop` ähnlich der FormRow hinzugefügt zur Darstellung des Loaders in einem Dialog.

2021-02-25 08:08 UTC, FreddyLeGrand requested changes

2021-02-25 08:08 UTC, FreddyLeGrand commented on src/components/Icon.stories.tsx
> +    <>
```suggestion
```

2021-02-25 08:08 UTC, FreddyLeGrand commented on src/components/Icon.stories.tsx
> +    </>
```suggestion
```

2021-02-25 08:08 UTC, FreddyLeGrand commented on src/components/Icon.tsx
> +type IconColor =
Wollen wir vielleicht auch noch `warning` mit hinzupacken?

2021-02-25 08:08 UTC, FreddyLeGrand commented on src/icons/index.ts
> +export { default as CheckCircleOutlineIcon } from '@material-ui/icons/CheckCircleOutline';
Bitte noch die neu implementierte `Icon, `Divider` und `Loader` Component hinzufügen

2021-02-25 08:08 UTC, FreddyLeGrand commented on src/layouts/GridRow.tsx
> +   * If `true`, the form row will have a bottom margin.
```suggestion
   * If `true`, the grid row will have a bottom margin.
```

2021-02-25 08:08 UTC, FreddyLeGrand commented on src/layouts/GridRow.tsx
> +   * If `true`, the form row will have a top margin.
```suggestion
   * If `true`, the grid row will have a top margin.
```

2021-02-25 09:20 UTC, antokro commented on src/components/Icon.tsx
> +type IconColor =
info habe ich auch noch hinzugefügt

2021-02-25 09:27 UTC, antokro commented on src/components/Icon.stories.tsx
> +    <>
Das ist der Hack damit das Icon und der Text "zusammen kleben" und nicht durch das Layout der FormRow auseinander gezogen werden. 
Falls dieser Fall mit Icon und Text wirklich öfter auftreten sollte, sollten wir vielleicht nochmal überlegen eine andere Art von Container zur Verfügung stellen oder die GridRow vielleicht erweitern um da mehr Layouts abbilden zu können, da die FormRow ja jetzt schon öfter für diverse Layouts verwendet wurde, die nichts mit einem Formular zu tun haben, oder was meinst du?

2021-02-25 09:36 UTC, FreddyLeGrand commented on src/components/Icon.stories.tsx
> +    <>
Hmmm... da würde ich mich anschließen, ja.. Die FormRow für solche Zwecke zu missbrauchen finde ich nicht gut, da sollten wir vielleicht wirklich einen neuen Container für vorsehen, ja.

2021-03-01 07:57 UTC, FreddyLeGrand approved these changes

2021-03-01 08:47 UTC, merged